name: "build"

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    permissions:
        contents: write
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: "{name}_{version}_firefox.xpi"
          ignoreFiles: '[ "img", "LICENSE", "README.md" ]'

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.web-ext-build.outputs.target }}